# Generated by Django 4.1.3 on 2023-01-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidores',
            name='esta_trabajando',
            field=models.BooleanField(default=True),
        ),
    ]
